### ISSUE TITLE
[cf-ssh] including "Getting" as a service

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-community/tmate-bootstrap#6]
``` yaml

---
applications:
- name: console-ssh
  command: curl http://tmate-bootstrap.cfapps.io | sh
  no-route: true
  services:
  - Getting
  - authentication
  - smtp
  env:
    CF_CC_API_URL: http://api.10.15.212.75.xip.io
...
```

The `Getting` service is accidentally being grepped out of the `cf s` output:

```
$ cf s
Getting services in org system / space console as admin...
OK

name             service         plan   bound apps   
authentication   user-provided          console-scheduler, console-workers, console   
smtp             user-provided          console-scheduler, console-workers, console   
```
